# Set update schedule for GitHub Actions
# Config enhances Dependabot GHE config to check GitHub Actions

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
